---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: galinec-org
  namespace: default
spec:
  secretName: galinec-org-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "galinec.org"
  dnsNames:
  - "galinec.org"
  - "*.galinec.org"